---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: tls-secret-injector
  labels:
    app.kubernetes.io/name: tls-secret-injector

spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tls-secret-injector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tls-secret-injector
    spec:
      serviceAccountName: tls-secret-injector

      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody

      containers:
        - name: controller
          image: {{ $.Values.image }}
          args:
            - --cert-dir=/var/run/serving-certificates/
            - --leader-election-resource={{ $.Release.Name }}
            - --leader-election-namespace={{ $.Release.Namespace }}
            - --log-level={{ $.Values.logLevel }}
            - --source-namespace={{ $.Values.sourceNamespace }}
          ports:
            - name: healthz
              containerPort: 8080
            - name: metrics
              containerPort: 8081
            - name: controller
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
            requests:
              cpu: {{ $.Values.resources.cpu }}
              memory: {{ $.Values.resources.memory }}
            limits:
              cpu: {{ $.Values.resources.cpu }}
              memory: {{ $.Values.resources.memory }}
          volumeMounts:
            - name: certificates
              mountPath: /var/run/serving-certificates
              readOnly: true

      volumes:
        - name: certificates
          secret:
            secretName: tls-secret-injector-tls
