---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration

metadata:
  name: tls-secret-injector
  labels:
    app.kubernetes.io/name: tls-secret-injector

webhooks:
  - name: ingress.tls-secret-injector.io
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    admissionReviewVersions:
      - v1
    timeoutSeconds: 5
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: tls-secret-injector
        namespace: {{ $.Release.Namespace }}
        path: /mutate
