---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tls-secret-injector
  labels:
    app.kubernetes.io/name: tls-secret-injector

rules:
  # Grant permissions to create events
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create

  # Grant permissions to allow Leader-Follower elections
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
