---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tls-secret-injector
  labels:
    app.kubernetes.io/name: tls-secret-injector

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tls-secret-injector

subjects:
  - kind: ServiceAccount
    name: tls-secret-injector
    namespace: {{ $.Release.Namespace }}
